# https://developers.home-assistant.io/docs/add-ons/configuration
name: "HTML-to-Image (H2I)"
description: "A local service to convert HTML to images, based on bybetas/h2i."
version: "1.0.0"
slug: "h2i"
init: false
arch:
  - amd64
ports:
  "80/tcp": 5005 # Exposes port 80 of the container to a configurable host port (default 5005)
ports_description:
  "80/tcp": "Web interface for the image generation API."
