name: Builder

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Add-on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.arch }}
        uses: home-assistant/builder@2024.08.2
        with:
          args: |
            --amd64 \
            --target /data/h2i \
            --image-name ghcr.io/${{ github.repository_owner }}/addon-h2i \
            --addon
